In [2]:
import numpy as np

In [3]:
# Fancy Idexing : 특정 인덱스를 여러 개를 선택해서 탐색하는 방법 
# 1차원 배열 
arr = np.array([5,10,15,20,25,30])
print(arr[[0,2,4]])

[ 5 15 25]


In [7]:
# 2차원 배열 
arr = np.array([[5,10,15,20,25],
               [30,35,40,45,50],
               [55,60,65,70,75]])
print(arr[[0,2], 2:])
print(arr[1:, [2,3]])

[[15 20 25]
 [65 70 75]]
[[40 45]
 [65 70]]
