In [1]:
import numpy as np
# 1차원 배열 
arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10)
print(arr)

print(arr[3])
print(arr[-1])

[0 1 2 3 4 5 6 7 8 9]
3
9


In [2]:
# 2차원 배열 
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(arr2, arr2.shape, arr2.ndim) # shape : 3X4, dimension : 2dim
print(arr2[0,3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
4


In [5]:
arr = np.array([0,1,2,3,4,5,6,7,8,9])
print(arr[3:8])
print(arr[3:])
print(arr[:7])
print(arr[:-1])

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


In [11]:
# 2차원 배열 
arr = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12]])
print(arr[0, :])
print(arr[:,1])


[1 2 3 4]
[ 2  6 10]


In [13]:
print(arr[:3,:])
print(arr[:2,2:])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]
