In [4]:
import numpy as np

In [6]:
# 2차원 배열 
arr = np.random.randint(15, size=(4,5))
print(arr)

[[ 8  9  3 10 12]
 [12  3  4  3 14]
 [ 9  6  9  1 12]
 [ 2 13 13 10 10]]


In [9]:
print(np.sort(arr))

[[ 3  8  9 10 12]
 [ 3  3  4 12 14]
 [ 1  6  9  9 12]
 [ 2 10 10 13 13]]


In [11]:
print(np.sort(arr, axis=0))

[[ 2  3  3  1 10]
 [ 8  6  4  3 12]
 [ 9  9  9 10 12]
 [12 13 13 10 14]]


In [12]:
print(np.sort(arr, axis=None))

[ 1  2  3  3  3  4  6  8  9  9  9 10 10 10 12 12 12 13 13 14]


In [ ]:
# argsort() 원소가 정렬되었을 때, 정렬된 원소의 원래 배열에서의 인덱스를 반환을 하게 된다. 
print(np.sort(arr, axis=1))
print(np.argsort(arr, axis=1))
