In [2]:
import numpy as np

In [4]:
# 1차원 배열의 정렬 
arr = np.random.randint(10, size=10)
print(arr)

[6 6 3 9 6 9 6 5 4 8]


In [5]:
print(np.sort(arr))

[3 4 5 6 6 6 6 8 9 9]


In [8]:
print(np.sort(arr))
print(np.sort(arr)[::-1])

[3 4 5 6 6 6 6 8 9 9]
[9 9 8 6 6 6 6 5 4 3]


In [10]:
arr = np.sort(arr)
print(arr)

[3 4 5 6 6 6 6 8 9 9]
