In [1]:
import numpy as np

In [2]:
# n차원 배열 연산법 
# 1차원 행렬 
arr1 = np.array([2,3,4])
arr2 = np.array([1,2,3])

print(np.dot(arr1,arr2))


20


In [3]:
# 2차원 행렬 
'''
[[a, b], [[e, f]     [[ae + bg  af + bh]
 [c, d],  [g, h]] =>  [ce + dg, cf + dh]]
'''
arr1 = np.array([[1, 2], 
                 [4, 5]])
arr2 = np.array([[1, 2], 
                 [0, 3]])
print(np.dot(arr1,arr2))

[[ 1  8]
 [ 4 23]]


In [4]:
# 절대값 
arr1 = np.array([[1,-2],
                 [-4,5]])
print(np.abs(arr1))

[[1 2]
 [4 5]]


In [8]:
# 올림 연산 
arr1 = np.array([[1.232,-23.2324],
                 [4.123123,-5.12312]])
print(np.ceil(arr1))

# 내림
print(np.floor(arr1))

# 반올림 
print(np.round(arr1))

# 버림 
print(np.trunc(arr1))

[[  2. -23.]
 [  5.  -5.]]
[[  1. -24.]
 [  4.  -6.]]
[[  1. -23.]
 [  4.  -5.]]
[[  1. -23.]
 [  4.  -5.]]
