In [2]:
import numpy as np

In [5]:
# 배열의 연산4 
# 비교 연산 
arr1 = np.array([[1,2,3],
                 [4,5,6]])
arr2 = np.array([[1,0,3],
                 [2,-5,4]])
print(arr1==arr2)
print(arr1 > arr2)
print(np.array_equal(arr1,arr2))

[[ True False  True]
 [False False False]]
[[False  True False]
 [ True  True  True]]
False


In [7]:
# 삼각 함수
arr = np.array([[1,2,3],
                [4,5,6]])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))
print(np.pi)


[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[ 0.54030231 -0.41614684 -0.9899925 ]
 [-0.65364362  0.28366219  0.96017029]]
[[ 1.55740772 -2.18503986 -0.14254654]
 [ 1.15782128 -3.38051501 -0.29100619]]
3.141592653589793
