In [1]:
import numpy as np

In [11]:
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
print(arr1)
print("\n")
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [13]:
# 덧셈 
print(arr1+arr2)
print(np.add(arr1,arr2))

[[11 22 33]
 [44 55 66]
 [77 88 99]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [14]:
# 뺄셈 
print(arr1-arr2)
print(np.subtract(arr1,arr2))

[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]
[[ -9 -18 -27]
 [-36 -45 -54]
 [-63 -72 -81]]


In [15]:
# 곱셈 
print(arr1*arr2)
print(np.multiply(arr1,arr2))

[[ 10  40  90]
 [160 250 360]
 [490 640 810]]
[[ 10  40  90]
 [160 250 360]
 [490 640 810]]


In [16]:
# 나눗셈 
print(arr1/arr2)
print(np.divide(arr1,arr2))

[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]
[[0.1 0.1 0.1]
 [0.1 0.1 0.1]
 [0.1 0.1 0.1]]


In [19]:
# 제곱 
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]])
print(arr1**2)
print(np.square(arr1))

# 제곱근 
print(np.sqrt(arr1))

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


In [21]:
# 몫
print(arr1//2)
# 나머지 
print(arr1%2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]
