In [8]:
import numpy as np

In [9]:
# 배열의 연산3
arr = np.array([[1,2,3],
                 [4,5,6]])

In [10]:
# min
print(np.min(arr))
print(arr.min())
print(arr.min(axis=0))
print(arr.min(axis=1))

1
1
[1 2 3]
[1 4]


In [16]:
# max
arr = np.array([[1,2,3],
                 [4,5,6]])
print(np.max(arr))
print(arr.max(axis=1))

6
[3 6]


In [22]:
# sum 
print(np.sum(arr))
print(arr.sum(axis=1))

# mean (평균)
print(np.mean(arr))
print(arr.mean(axis=0))
print(arr.mean(axis=1))

21
[ 6 15]
3.5
[2.5 3.5 4.5]
[2. 5.]


In [30]:
# std 표준편차
print(np.std(arr))
print(arr.std(axis=0))
print(arr.std(axis=1))

# cumsum 누적값
print(np.cumsum(arr))
print(arr.cumsum(axis=1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]
[ 1  3  6 10 15 21]
[[ 1  3  6]
 [ 4  9 15]]


In [35]:
# median 중앙값
print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

[2.5 3.5 4.5]
[2. 5.]
